sofascore:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: foot-analyse
      dataset: foot_data
      location: US
      keyfile: /opt/airflow/credentials/credentials.json
